@Library('shared-library') _

import com.aws.ce.pipeline.GlobalVars

def config = [name: 'Newman', dayOfWeek: 'Friday']
pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                helloWorld(config)
            }
        }
    }
}
